# Generated by Django 3.1.3 on 2020-12-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_upload_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='upload',
            field=models.FileField(upload_to=''),
        ),
    ]
