# Generated by Django 3.1.3 on 2020-12-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_upload_file', '0002_auto_20201215_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='upload',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
