# Generated by Django 3.1.3 on 2020-12-16 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_upload_file', '0003_auto_20201215_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
