# Generated by Django 3.1.3 on 2020-12-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_upload_file', '0005_article_reporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publi_date',
            new_name='pub_date',
        ),
    ]
